### ISSUE TITLE
Missing geo-layer elements

### ISSUE THREAD

**Issue by ayarov** [ayarov/fuxit#4]
The geo-search tab should display the layers, while each layer is clickable and when it's clicked, the appropriate geo-elements are displayed on the map.
Also, allow more than one geo-layer to be selected at the same time.

**Comment by reggev** [comment]
added support for multiple layers, only one active layer and polygon are available for now
commit: 93d8796fd2a0a974f337bd88c65c94a2e8c59b69
moving to a new issue for multiple selection
